name    'theforeman-chef'
version '0.0.1'
source 'git://github.com/theforeman/puppet-chef'
author 'theforeman'
license 'GPLv3+'
summary 'Chef server and plugins configuration'
description 'Module for installing Chef server and related Foreman plugins configuration'
project_page 'http://github.com/theforeman/foreman-installer'

dependency 'computology/packagecloud', '>= 0.2.0'
